// Icon assets exported directly from the Figma file (node 994:470).
// Served as static files by server.ts at /icons/*, referenced by stable URL
// so they render inside isolated <img> documents (no mask/filter id clashes).
export const icons = {
  flashLogo: "/icons/flash-logo.svg",
  sidebarToggle: "/icons/sidebar-toggle.svg",
  home: "/icons/home.svg",
  chats: "/icons/chats.svg",
  projects: "/icons/projects.svg",
  watchlist: "/icons/watchlist.svg",
  workflows: "/icons/workflows.svg",
  workbench: "/icons/workbench.svg",
  backtests: "/icons/backtests.svg",
  send: "/icons/send.svg",
  sendArrow: "/icons/send-arrow.svg",
  scrollHint: "/icons/scroll-hint.svg",
  profileAvatar: "/icons/profile-avatar.png",
  profileMenu: "/icons/profile-menu.svg",
  spotlight: "/icons/spotlight.png",
  rdDowJones: "/icons/rd-dowjones.png",
  rdAmca: "/icons/rd-amca.png",
  rdKarp: "/icons/rd-karp.png",
  rdAdani: "/icons/rd-adani.png",
  rdZomato: "/icons/rd-zomato.png",
  rdParas: "/icons/rd-paras.png",
  rdMarket: "/icons/rd-market.png",
  rdIndiaUs: "/icons/rd-indiaus.png",
  rdTreemap: "/icons/rd-treemap.png",
  wlAdaniEnt: "/icons/wl-adanient.png",
  wlAdaniPower: "/icons/wl-adanipower.png",
  wlAbCapital: "/icons/wl-abcapital.png",
  wlAmbujaCem: "/icons/wl-ambujacem.png",
  wlAsianPaint: "/icons/wl-asianpaint.png",
  wlAshokLey: "/icons/wl-ashokley.png",
  wlAxisBank: "/icons/wl-axisbank.png",
} as const;
